#vars file

aws_group: "DockerHost"
aws_instance_type: "t2.micro"
aws_image_id: "ami-1e299d7e"
aws_keypair: "tikal"
aws_wait_time: 500
aws_instnce_name: "docker_host"
aws_vpc_subnet_id: "subnet-5026c519"
aws_region: "us-west-2"
inv_file: "dockerhost_inventory"
project_name: "idan"
aws_vpc_id: "vpc-802981e7"
